[package]
name = "rcpumon"
version = "0.1.0"
authors = ["null_ptr"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.0.1"
crossterm = "0.17.4"
tui = "0.9.1"
#termion = "1.5.5"
futures = "0.3.4"
